// functions/src/types/notification.ts
export interface Notification {
  id: string; // Auto-generated by Firestore
  type: "low_stock" | "payment_failed" | "order_flagged";
  severity: "info" | "warning" | "critical";
  title: string; // e.g., "Low Stock: Wireless Mouse"
  message: string; // e.g., "Only 2 units left in Warehouse A."

  // Deep-linking: Tells the frontend exactly where to route the admin
  targetEntity: {
    collection: "products" | "orders";
    docId: string;
  };

  // Track who has seen it to calculate the "unread" badge count
  readBy: string[]; // Array of admin UIDs

  createdAt: any; // Firestore Timestamp
  resolvedAt: any | null; // Firestore Timestamp (null if still active)
}
