import { Timestamp } from "firebase-admin/firestore";

export type PaymentStatus = "pending" | "success" | "failed" | "refunded" | "abandoned";

export interface Payment {
  id: string; // Firestore document ID
  orderId: string; // Link to the Order
  customerId?: string; // Null if guest
  
  // Paystack Specifics
  paystackReference: string; // Unique reference generated by Paystack
  paystackAuthorizationCode?: string; // For future recurring charges/tokenization
  paymentChannel: "card" | "bank" | "ussd" | "qr" | "mobile_money";
  
  // Financials
  amountCents: number;
  currency: string; // e.g., "ZAR", "NGN", "GHS"
  
  // State
  status: PaymentStatus;
  failureReason?: string;
  
  // Metadata
  customerEmail: string;
  customerName?: string;
  
  createdAt: Timestamp;
  updatedAt: Timestamp;
  completedAt?: Timestamp;
}